# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'ChromeCastRemote' do
pod 'google-cast-sdk'
end

target 'ChromeCastRemoteTests' do

end

target 'ChromeCastRemoteUITests' do

end

